#!/usr/bin/env ruby
require 'optparse'
require File.expand_path('scron', File.dirname(__FILE__))

ARGV.options do |o|
  o.set_summary_indent('  ')
  o.banner =    "Usage: #{File.basename($0)} [OPTION]"
  o.define_head "Scheduler for laptops/machines which aren't on 24/7"
  o.on('-e', '--edit', 'edit jobs') { Scron.edit; exit }
  o.on('-r', '--run', 'run jobs') { Scron.run; exit }
  o.on('-h', '--help', 'show this help message') { puts o; exit }
  o.parse!
  puts o
end
